# Generated by Django 5.2 on 2026-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
