# Generated by Django 5.2 on 2026-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_mediafile_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='feed_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]

