# Generated by Django 5.2 on 2026-08-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_youtubechannel_feed_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='channel_profiles/'),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='feed_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
