# Generated by Django 5.2 on 2026-08-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0005_mediafile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='video_id',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
