# Generated by Django 5.2 on 2026-09-08 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0007_favoritetrack_listeninghistory_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_entry', to='downloader.youtubechannel')),
            ],
            options={
                'ordering': ['-followed_at'],
            },
        ),
    ]
