# Generated by Django 5.2 on 2026-09-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0008_followedartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='downloader.youtubechannel'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
