# Generated by Django 5.2 on 2026-09-09 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0009_playlist_channel_playlist_playlist_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritetrack',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followedartist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='downloader.mediafile'),
        ),
        migrations.AlterField(
            model_name='followedartist',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_entries', to='downloader.youtubechannel'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritetrack',
            unique_together={('user', 'media_file')},
        ),
        migrations.AlterUniqueTogether(
            name='followedartist',
            unique_together={('user', 'channel')},
        ),
    ]
