# Generated by Django 5.2 on 2026-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0010_favoritetrack_user_followedartist_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloaderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_file', models.FileField(blank=True, help_text='Upload your YouTube cookies.txt file to bypass YouTube datacenter bot detection', null=True, upload_to='cookies/')),
                ('cookies_text', models.TextField(blank=True, default='', help_text='Or paste your cookies.txt content directly here')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Cookie / Downloader Setting',
                'verbose_name_plural': 'YouTube Cookie / Downloader Settings',
            },
        ),
    ]
