services:
  web:
    build:
      context: .
      args:
        VITE_SPOTIFY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
        VITE_SPOTIFY_REDIRECT_URL: ${VITE_SPOTIFY_REDIRECT_URL}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_LOCAL_IP: ${VITE_LOCAL_IP}
    restart: always
    container_name: 'spotify-web'
    ports:
      - "${WEB_PORT:-3001}:80"
    depends_on:
      - api

  api:
    build:
      context: ./youtube-audio-api
    restart: always
    container_name: 'spotify-api'
    ports:
      - "${API_PORT:-8001}:8000"
    volumes:
      - spotify-media:/app/media

volumes:
  spotify-media:
