services:
  web:
    image: ${FRONTEND_IMAGE}
    restart: always
    container_name: spotify-web
    ports:
      - "${WEB_PORT:-3001}:80"
    depends_on:
      - api

  api:
    image: ${BACKEND_IMAGE}
    restart: always
    container_name: spotify-api
    ports:
      - "${API_PORT:-8001}:8000"
    volumes:
      - spotify-media:/app/media

volumes:
  spotify-media:
