"""
Django settings for ytaudio project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env without external dependencies
def _load_env(path):
    if not os.path.exists(path):
        return
    try:
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                k, v = line.split('=', 1)
                k = k.strip()
                v = v.strip()
                if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                    v = v[1:-1]
                if k not in os.environ:
                    os.environ[k] = v
    except Exception:
        pass

_load_env(BASE_DIR.parent / '.env')
_load_env(BASE_DIR / '.env')

LOCAL_IP = os.getenv('LOCAL_IP') or os.getenv('VITE_LOCAL_IP') or '127.0.0.1'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w_!==+-_sdrs74ym0+!%l6$zu5h=wsdkt0$l6_h9%jt_61ahw6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['youtube-audio-api-production-06e5.up.railway.app', 'localhost', '127.0.0.1', 'testserver', '.devtunnels.ms', '*']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'background_task',

    'downloader',
    'accounts',
    'social',
    'rooms',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ytaudio.urls'
# Add these settings for background tasks
MAX_ATTEMPTS = 2  # Maximum number of attempts for a task
MAX_RUN_TIME = 36  # Maximum runtime for a task in seconds (1 hour)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates"/"downloader"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ytaudio.wsgi.application'
ASGI_APPLICATION = 'ytaudio.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_DIR = BASE_DIR / 'database'
if not DB_DIR.exists():
    try:
        DB_DIR.mkdir(exist_ok=True)
    except Exception:
        pass

if DB_DIR.exists() and os.access(DB_DIR, os.W_OK):
    DB_FILE = DB_DIR / 'db.sqlite3'
    if (BASE_DIR / 'db.sqlite3').exists() and not DB_FILE.exists():
        try:
            import shutil
            shutil.copy2(BASE_DIR / 'db.sqlite3', DB_FILE)
        except Exception:
            pass
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DB_FILE if (DB_FILE.exists() or os.access(DB_DIR, os.W_OK)) else BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (user uploads like audio)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Add REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Login URL settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'channel_list'
LOGOUT_REDIRECT_URL = 'login'

# ── CORS (Cross-Origin Resource Sharing) ────────────────────────────────────
# Allow the React dev server to call the Django API with cookies.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Allow any local network IP origin matching 192.168.*.* or 10.*.*.*
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://localhost:\d+$",
    r"^http://192\.168\.\d+\.\d+(:\d+)?$",
    r"^http://10\.\d+\.\d+\.\d+(:\d+)?$",
]

CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://127.0.0.1:3004',
    'http://localhost:3004',
    'http://127.0.0.1:5173',
    'http://localhost:5173',
]
if LOCAL_IP and LOCAL_IP not in ('127.0.0.1', 'localhost'):
    for port in ('3000', '3004', '5173', '8000', '8004'):
        url = f'http://{LOCAL_IP}:{port}'
        if url not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(url)

# Session and CSRF cookie settings (unique names prevent clash with other apps like algoflow on 144.91.72.44)
SESSION_COOKIE_NAME = 'sportify_sessionid'
CSRF_COOKIE_NAME = 'sportify_csrftoken'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # False so cookies work over plain HTTP in dev/vps
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 2592000  # 30 days session validity

# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://127.0.0.1:3004',
    'http://localhost:3004',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8004',
    'http://localhost:8004',
    'http://127.0.0.1:5173',
    'http://localhost:5173',
    'https://*.devtunnels.ms',
    'http://*.devtunnels.ms',
    'http://144.91.72.44',
    'http://144.91.72.44:8004',
    'http://144.91.72.44:3004',
    'http://144.91.72.44:8000',
    'http://144.91.72.44:3000',
    'https://144.91.72.44',
    'https://144.91.72.44:8004',
    'https://144.91.72.44:3004',
]

hosts_to_trust = [h for h in [
    LOCAL_IP,
    os.getenv('SERVER_HOST'),
    os.getenv('HOST'),
    os.getenv('SSH_HOST'),
] if h and h not in ('127.0.0.1', 'localhost', '144.91.72.44')]

for h in hosts_to_trust:
    for port in ('3000', '3004', '5173', '8000', '8004'):
        for proto in ('http', 'https'):
            origin = f'{proto}://{h}:{port}'
            if origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(origin)
            if origin not in CORS_ALLOWED_ORIGINS:
                CORS_ALLOWED_ORIGINS.append(origin)
    for proto in ('http', 'https'):
        origin = f'{proto}://{h}'
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

env_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if env_csrf:
    for item in env_csrf.split(','):
        item = item.strip()
        if item and item not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(item)

